#spring:
#  application:
#    name: gateway-service
#  cloud:
#    kubernetes:
#      client:
#        namespace: default
#      discovery:
#        discovery-server-url: http://spring-cloud-kubernetes-discoveryserver
#        all-namespaces: true
#        enabled: true
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#      routes:
#        - id: order
#          uri: lb://order-service
#          predicates:
#            - Path=/order/**
#          filters:
#            - RewritePath=/order/(?<path>.*), /\${path}
#        - id: payment
#          uri: lb://payment-service
#          predicates:
#            - Path=/payment/**
#          filters:
#            - RewritePath=/payment/(?<path>.*), /\${path}
#logging:
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
#  level:
#    org.springframework.cloud.gateway: DEBUG

spring:
  application:
    name: gateway
  cloud:
    kubernetes:
      client:
        namespace: default
      discovery:
        discovery-server-url: http://spring-cloud-kubernetes-discoveryserver
        all-namespaces: true
        enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: order
          uri: lb://order-service
          predicates:
            - Path=/order/**
          filters:
            - RewritePath=/order/(?<path>.*), /$\{path}
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"